name: Pubish Docker image
on:
    push:
        branches:
            - master
env:
    IMAGE_NAME: your2020
jobs:
    push_to_registries:
        name: Push Docker image
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
            with:
                submodules: true
          - name: Push to Docker Hub
            uses: docker/build-push-action@v1
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                repository: drkno/your2020
                tag_with_ref: true
